# Generated by Django 5.2.6 on 2025-10-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('netwark', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('desc', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('delet_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
